
SELECT * FROM financial_loan

--TOTAL LOAN APPLICATION
SELECT COUNT(DISTINCT ID) AS TOTAL_LOAN_APPLICATION FROM financial_loan

--MTD
SELECT COUNT(DISTINCT ID) AS TOTAL_LOAN_APPLICATION FROM financial_loan	
WHERE MONTH(issue_date) = 12

--PMTD
SELECT COUNT(DISTINCT ID) AS TOTAL_LOAN_APPLICATION FROM financial_loan
WHERE MONTH(issue_date) = 11

--MOM
WITH CTE_MTD AS (
				SELECT COUNT(DISTINCT ID) AS MTD   FROM financial_loan	
				WHERE MONTH(issue_date) = 12 
				),
 CTE_PMTD AS (
				SELECT COUNT(DISTINCT ID) AS PMTD   FROM financial_loan
				WHERE MONTH(issue_date) = 11 
				)
SELECT MTD, PMTD, (MTD - PMTD)*100.0/PMTD AS MOM FROM CTE_MTD,CTE_PMTD



--TOTAL FUNDED AMOUNT
SELECT SUM(LOAN_AMOUNT) AS TOTAL_FUNDED_AMOUNT  FROM financial_loan

--MTD
SELECT SUM(LOAN_AMOUNT) AS TOTAL_FUNDED_AMOUNT  FROM financial_loan
WHERE MONTH(issue_date) = 12

--PMTD
SELECT SUM(LOAN_AMOUNT) AS TOTAL_FUNDED_AMOUNT  FROM financial_loan
WHERE MONTH(issue_date) = 11

--MOM
WITH CTE_MTD AS (
				SELECT SUM(LOAN_AMOUNT) AS MTD   FROM financial_loan	
				WHERE MONTH(issue_date) = 12 
				),
 CTE_PMTD AS (
				SELECT SUM(LOAN_AMOUNT) AS PMTD   FROM financial_loan
				WHERE MONTH(issue_date) = 11 
				)
SELECT MTD, PMTD, (MTD - PMTD)*100.0/PMTD AS MOM FROM CTE_MTD,CTE_PMTD



--TOTAL AMOUNT RECEIVED
SELECT SUM(TOTAL_PAYMENT) AS TOTAL_AMOUNT_RECEIVED FROM financial_loan

--MTD
SELECT SUM(TOTAL_PAYMENT) AS TOTAL_AMOUNT_RECEIVED FROM financial_loan
WHERE MONTH(issue_date) = 12

--PMTD
SELECT SUM(TOTAL_PAYMENT) AS TOTAL_AMOUNT_RECEIVED FROM financial_loan
WHERE MONTH(issue_date) = 11

--MOM
WITH CTE_MTD AS (
				SELECT SUM(TOTAL_PAYMENT) AS MTD   FROM financial_loan	
				WHERE MONTH(issue_date) = 12 
				),
 CTE_PMTD AS (
				SELECT SUM(TOTAL_PAYMENT) AS PMTD   FROM financial_loan
				WHERE MONTH(issue_date) = 11 
				)
SELECT MTD, PMTD, (MTD - PMTD)*100.0/PMTD AS MOM FROM CTE_MTD,CTE_PMTD


--AVERAGE INTEREST RATE
SELECT ROUND(AVG(INT_RATE)*100,2) AS AVG_INT_RATE FROM financial_loan

--MTD
SELECT ROUND(AVG(INT_RATE)*100,2) AS AVG_INT_RATE FROM financial_loan
WHERE MONTH(issue_date) = 12

--PMTD
SELECT ROUND(AVG(INT_RATE)*100,2) AS AVG_INT_RATE FROM financial_loan
WHERE MONTH(issue_date) = 11 

--MOM
WITH CTE_MTD AS (
				SELECT ROUND(AVG(INT_RATE)*100,2) AS MTD   FROM financial_loan	
				WHERE MONTH(issue_date) = 12 
				),
 CTE_PMTD AS (
				SELECT ROUND(AVG(INT_RATE)*100,2) AS PMTD   FROM financial_loan
				WHERE MONTH(issue_date) = 11 
				)
SELECT MTD, PMTD, (MTD - PMTD)*100.0/PMTD AS MOM FROM CTE_MTD,CTE_PMTD



--AVERAGE DEBT TO INCOME RATION
SELECT ROUND(AVG(DTI)*100,2) AS AVG_DTI FROM financial_loan

--MTD
SELECT ROUND(AVG(DTI)*100,2) AS AVG_DTI FROM financial_loan
WHERE MONTH(issue_date) = 12

--PMTD
SELECT ROUND(AVG(DTI)*100,2) AS AVG_DTI FROM financial_loan
WHERE MONTH(issue_date) = 11

--MOM
WITH CTE_MTD AS (
				SELECT ROUND(AVG(DTI)*100,2) AS MTD   FROM financial_loan	
				WHERE MONTH(issue_date) = 12 
				),
 CTE_PMTD AS (
				SELECT ROUND(AVG(DTI)*100,2) AS PMTD   FROM financial_loan
				WHERE MONTH(issue_date) = 11 
				)
SELECT MTD, PMTD, (MTD - PMTD)*100.0/PMTD AS MOM FROM CTE_MTD,CTE_PMTD

--GOOD LOAN APPLICATION PERCENTAGE 
SELECT (COUNT(CASE WHEN LOAN_STATUS = 'Fully Paid' OR  LOAN_STATUS = 'Current' THEN ID END) *100) /
COUNT(ID) AS GOOD_LOAN_PERCENTAGE FROM financial_loan


--GOOD LOAN APPLICATION PERCENTAGE
SELECT COUNT(ID)AS GOOD_LOAN_APPLICATION FROM financial_loan
WHERE LOAN_STATUS IN ('Fully Paid', 'Current')

--GOOD LOAN FUNDED AMOUNT
SELECT SUM(LOAN_AMOUNT)AS GOOD_LOAN_FUNDED_AMOUNT FROM financial_loan
WHERE LOAN_STATUS IN ('Fully Paid', 'Current') 

--GOOD LOAN TOTAL RECEIVED AMOUNT
SELECT SUM(TOTAL_PAYMENT) AS GOOD_LOAN_TOTAL_REVEIVED_AMOUNT FROM financial_loan
WHERE LOAN_STATUS IN ('Fully Paid', 'Current')

--BAD LOAN APPLICATION PERCENTAGE
SELECT (COUNT(CASE WHEN LOAN_STATUS = 'Charged Off' THEN ID END)*100) /
COUNT(ID) AS BAD_LAON_APPLICATION_PERCENTAGE FROM financial_loan

--BAD LOAN APPLICATION
SELECT COUNT(ID) AS BAD_LOAN_APPLICATION FROM financial_loan
WHERE LOAN_STATUS = 'Charged Off'

--BAD LOAN FUNDED AMOUNT
SELECT SUM(LOAN_AMOUNT) AS BAD_LOAN_FUNDED_AMOUNT FROM financial_loan
WHERE LOAN_STATUS = 'Charged Off'

--BAD LOAN TOTAL RECEIVED AMOUNT
SELECT SUM(TOTAL_PAYMENT) AS BAD_LOAN_TOTAL_RECEIVED_AMOUNT FROM financial_loan
WHERE LOAN_STATUS = 'Charged Off'

--MONTHLY TRENDS BY ISSSUE DATE
SELECT MONTH(ISSUE_DATE) MONTH_NUMBER,
		DATENAME(MONTH,ISSUE_DATE)  MONTH_NAME,
		COUNT(ID) TOTAL_LOAN_APPLICATION,
		SUM(LOAN_AMOUNT) TOTAL_FUNDED_AMOUNT,
		SUM(TOTAL_PAYMENT) TOTAL_AMOUNT_RECEIVE
		FROM financial_loan
		GROUP BY MONTH(ISSUE_DATE) , DATENAME(MONTH,ISSUE_DATE)
		ORDER BY MONTH(ISSUE_DATE)

--REGIONAL ANALYSIS BY STATE
SELECT ADDRESS_STATE AS STATE,
		COUNT(ID) TOTAL_LOAN_APPLICATION,
		SUM(LOAN_AMOUNT) TOTAL_FUNDED_AMOUNT,
		SUM(TOTAL_PAYMENT) TOTAL_AMOUNT_RECEIVE
		FROM financial_loan
		GROUP BY ADDRESS_STATE
		ORDER BY ADDRESS_STATE 

--LOAN TERM ANALYSYS
SELECT TERM AS TERM,
		COUNT(ID) TOTAL_LOAN_APPLICATION,
		SUM(LOAN_AMOUNT) TOTAL_FUNDED_AMOUNT,
		SUM(TOTAL_PAYMENT) TOTAL_AMOUNT_RECEIVE
		FROM financial_loan
		GROUP BY TERM
		ORDER BY TERM 

--EMPLOYEE LENGTH ANALYSIS
SELECT EMP_LENGTH AS EMPLOYEE_LENGTH, 
		COUNT(ID) TOTAL_LOAN_APPLICATION,
		SUM(LOAN_AMOUNT) TOTAL_FUNDED_AMOUNT,
		SUM(TOTAL_PAYMENT) TOTAL_AMOUNT_RECEIVE
		FROM financial_loan
		GROUP BY EMP_LENGTH
		ORDER BY EMP_LENGTH 

--LOAN PURPOSE BREAKDOWN
SELECT PURPOSE AS PURPOSE,
		COUNT(ID) TOTAL_LOAN_APPLICATION,
		SUM(LOAN_AMOUNT) TOTAL_FUNDED_AMOUNT,
		SUM(TOTAL_PAYMENT) TOTAL_AMOUNT_RECEIVE
		FROM financial_loan
		GROUP BY PURPOSE
		ORDER BY PURPOSE      

--HOME OWNERSHIP ANALYSIS
SELECT HOME_OWNERSHIP AS HOME_OWNERSHIP,
		COUNT(ID) TOTAL_LOAN_APPLICATION,
		SUM(LOAN_AMOUNT) TOTAL_FUNDED_AMOUNT,
		SUM(TOTAL_PAYMENT) TOTAL_AMOUNT_RECEIVE
		FROM financial_loan
		GROUP BY HOME_OWNERSHIP
		ORDER BY HOME_OWNERSHIP      
